services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    environment:
      DATABASE_PATH: /app/data/fuckcancer.db
    volumes:
      - ./server/data:/app/data

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
